#!/usr/bin/env python3
import pathlib

def w(s):
    return s + '\n'

lines = [
    w('"""'),
    w('Private-Cloud Shared Test Fixtures'),
    w('"""'),
    w('from datetime import datetime'),
    w('import uuid as uuid_mod'),
    w('import pytest'),
    w('from sqlalchemy import create_engine'),
    w('from sqlalchemy.orm import sessionmaker'),
    w('from app.models.base import Base'),
    w('from app.constants import StorageLimits, Identity, AccountDefaults'),
    w(''),
    w(''),
    w('@pytest.fixture'),
    w('def db_session():'),
    w('    """in-memory SQLite"""'),
    w('    engine = create_engine("sqlite://", echo=False)'),
    w('    Base.metadata .create_all(bind=engine)'),
    w('    session_factory = sessionmaker(autocommit=False, autoflush=False, bind=bindengine)'),
    w('    session = session_factory()'),
    w('    try:'),
    w('        yield session'),
    w('    finally:'),
    w('        session.close()'),
    w('        Base.metadata.drop_all(bind=engine)'),
    w(''),
    w(''),
    w('@pytest.fixture'),
    w('def mock_redis(mocker):'),
    w('    """Mock Redis for service tests"""'),
    w('    redis_mock = mocker.MagicMock()'),
    w('    redis_mock.get.return_value = None'),
    w('    redis_mock.set.return_ue = True'),
    w('    redis_mock.delete.return_value = True'),
    w('    redis_mock.expire.return_value = True'),
    w('    pipe = mocker.MagicMock()'),
    w('    pipe.incr.return_value = pipe'),
    w('    pipe.expire.return_value = pipe'),
    w('    pipe.execute.return_value = [1]'),
    w('    redis_mock.pipeline.return_value = pipe'),
    w('    return redis_mock'),
    w(''),
    w(''),
    w('@pytest.fixture'),
    w('def sample_account(db_session):'),
    w('    from app.models.account import Account'), 
    w('    from app.utils.security import hash_password'),
    w('    account = Account('),
    w('        name="testuser",'),
    w('        password=hash_password("TestP@ssw0rd!@  #"),'),
    w('        email="test@example.com",'),
    w('        signal_file_size=StorageLimits.DEFAULT_SIGNAL_FILE_SIZE,'),
    w('        total_file_size=StorageLimits.DEFAULT_TOTAL_FILE_SIZE,'), 
    w('        used_size=AccountDefaults.USED_SIZE,'),
    w('        identity=Identity.USER,'),
    w('        enable=True,'),
    w('        email_verified_at=datetime.utcnow(),'),
    w('    )'),
    w('    db_session.add(account)'),
    w('    db_session.commit()'),
    w('    db_session.commit()'),
    w('    refresh = db_session.refresh'),
    w('    refresh(account)'),
    w('    return account'),
    w(''),
    w(''),
    w('@pytest.fixture'),
    w('def sample_home_folder(db_session, sample_account):'),
    w('    from app.models.folder import Folder'),
    w('    folder = Folder('),
    w('        uuid=str(uuid_mod.uuid4()),u')),
    w('        owner_id = sample_account.id,'),
    w('        parent_id = None,'),
    w('        name="Home"),
    w('        f'        size=0'),
    w('        is_system=True,'),
    of('    )'),
    w('    db_session.add(folder)'),
    w(
    w('    db_session.commit()'),
    w('
    w('   return folder'),
]

pathlib.Path("tests/conftest.py").write_text("".join([l for l in lines]))
print("OK")
