"""init

Revision ID: 30d0b9a02f68
Revises: 004
Create Date: 2026-06-10 20:21:50.307123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '30d0b9a02f68'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_index(op.f('ix_files_owner_id'), table_name='files')
    op.drop_index(op.f('ix_files_parent_folder_id'), table_name='files')
    op.drop_index(op.f('ix_files_uuid'), table_name='files')
    op.drop_index(op.f('uq_files_shared_non_null'), table_name='files')
    op.drop_index(op.f('uuid'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_folders_deleted_at'), table_name='folders')
    op.drop_index(op.f('ix_folders_owner_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_parent_id'), table_name='folders')
    op.drop_index(op.f('ix_folders_uuid'), table_name='folders')
    op.drop_index(op.f('uq_folders_shared_non_null'), table_name='folders')
    op.drop_index(op.f('uuid'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('signal_file_size', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('total_file_size', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('used_size', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('identity', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email_verified_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('delete_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('last_sign_in_date', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'accounts', ['name'], unique=True)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=False)
    op.create_index(op.f('email'), 'accounts', ['email'], unique=True)
    op.create_table('folders',
    sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('size', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('shared', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('is_system', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], name=op.f('folders_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.uuid'], name=op.f('folders_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uuid'), 'folders', ['uuid'], unique=True)
    op.create_index(op.f('uq_folders_shared_non_null'), 'folders', ['shared'], unique=True)
    op.create_index(op.f('ix_folders_uuid'), 'folders', ['uuid'], unique=False)
    op.create_index(op.f('ix_folders_parent_id'), 'folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_folders_owner_id'), 'folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_folders_deleted_at'), 'folders', ['deleted_at'], unique=False)
    op.create_table('files',
    sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_folder_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('size', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('mime_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('storage_path', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('shared', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=False),
    sa.Column('deleted_at', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['accounts.id'], name=op.f('files_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['folders.uuid'], name=op.f('files_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uuid'), 'files', ['uuid'], unique=True)
    op.create_index(op.f('uq_files_shared_non_null'), 'files', ['shared'], unique=True)
    op.create_index(op.f('ix_files_uuid'), 'files', ['uuid'], unique=False)
    op.create_index(op.f('ix_files_parent_folder_id'), 'files', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_files_owner_id'), 'files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
